config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :dogs, only: [:index, :show, :new, :create ] do
  resources :bookings, only: [:create]

end

resources :bookings, only: [:index, :update]

namespace :owner do
  resources :bookings, only: [:index]
end



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dog
  validates :start_date, presence: true
  validates :end_date, presence: true
  enum status: [ :pending, :accepted, :rejected ]
  scope :past, -> { where('end_date < ?', Date.today) }
  scope :future, -> { where('start_date >= ?', Date.today) }
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  validates :name,  presence: true
  validates :price, presence: true
  validates :breed, presence: true
  validates :size,  presence: true
  validates :age, presence: true
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dogs
  has_many :bookings
  has_many :bookings_as_owner, through: :dogs, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @future_bookings = current_user.bookings.future
    @past_bookings = current_user.bookings.past
  end

  def new
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new
  end

  def create
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new(booking_params)
    @booking.dog = @dog
    @booking.user = current_user
      if @booking.save
        redirect_to bookings_path
      else
        render "dogs/show", status: :unprocessable_entity
      end
     end

     private

     def booking_params
      params.require(:booking).permit(:start_date, :end_date, :status)
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
    @booking = Booking.new
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    if @dog.save
      redirect_to dog_path(@dog)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :photo, :breed, :age, :size, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@dog, @booking] do |f| %>
  <%#= f.input :rating, input_html: { min: 0, max: 5 } %>
  <%= f.input :start_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :end_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: 'btn btn-primary mt-2' %>
<% end %>

app/views/bookings/_form_html.erb
<%= simple_form_for [@dog, @booking] do |f| %>
  <%#= f.input :rating, input_html: { min: 0, max: 5 } %>
  <%= f.input :start_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :end_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: 'btn btn-primary mt-2' %>
<% end %>

app/views/bookings/create.html.erb
<h1>here</h1>

app/views/bookings/index.html.erb
<div class="container">
  <h1>Your Bookings</h1>
</div>
<ul class="nav tabs-underlined" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <span class="nav-link tab-underlined active" id="bookings-tab" data-bs-toggle="tab" data-bs-target="#bookings-tab-pane" role="tab" aria-controls="bookings-tab-pane" aria-selected="true">Future Bookings</span>
  </li>
  <li class="nav-item" role="presentation">
    <span class="nav-link tab-underlined" id="requests-tab" data-bs-toggle="tab" data-bs-target="#requests-tab-pane" role="tab" aria-controls="requests-tab-pane" aria-selected="false">Past Bookings</span>
  </li>
  <li class="nav-item" role="presentation">
    <span class="nav-link tab-underlined" id="conversations-tab" data-bs-toggle="tab" data-bs-target="#conversations-tab-pane" role="tab" aria-controls="conversations-tab-pane" aria-selected="false">Pending</span>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade py-3 show active" id="bookings-tab-pane" role="tabpanel" aria-labelledby="bookings-tab" tabindex="0">
    <h2>Future  Bookings</h2>
    <% @future_bookings.each do |booking| %>
      <div class="card-product">
        <%= image_tag booking.dog.image_url %>
        <div class="card-product-infos">
          <h2> Dog Name: <%=booking.dog.name  %></h2>
          <p> Start Date: <%= booking.start_date %></p>
          <p> End Date: <%= booking.end_date %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="tab-pane fade py-3" id="requests-tab-pane" role="tabpanel" aria-labelledby="requests-tab" tabindex="0">
    <h2>Past Bookings</h2>
    <% @past_bookings.each do |booking| %>
      <div class="card-product">
        <%= image_tag booking.dog.image_url %>
        <div class="card-product-infos">
          <h2> Dog Name: <%=booking.dog.name  %></h2>
          <p> Start Date: <%= booking.start_date %></p>
          <p> End Date: <%= booking.end_date %></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="tab-pane fade py-3" id="conversations-tab-pane" role="tabpanel" aria-labelledby="conversations-tab" tabindex="0">
  </div>
</div>

app/views/dogs/index.html.erb
<div class="container my-5">
  <h1>Discover our cute dogs</h1>
  <div class="cards">
    <% @dogs.each do |dog| %>
      <div class= "dog-cards" style="background-image">
        <%= dog.name %>
        <%= image_tag dog.image_url , class: "dogs-image"%>
        <%= link_to 'PET ME', dog_path(dog), class: 'card-category-link'%>
      </div>
    <% end %>
  </div>
</div>

app/views/dogs/show.html.erb
<div class="container">
<div class="d-flex justify-content-center">
<h1 class="-center p-4"><%= @dog.name %>'s Profile</h1>
</div>

<div class="container d-flex justify-content-center">
  <%= image_tag @dog.image_url, width: "300", height: "fit", class: "rounded-5" %>
  <div class="ms-5 border border-3 rounded p-3 align-center">
  <p class="p-2 ">🐾 <%= @dog.name %></p>
  <p class="p-2">🐾 <%= @dog.age %></p>
  <p class="p-2">🐾 <%= @dog.breed %></p>
  <p class="p-2">🐾 <%= @dog.size.capitalize %></p>
  <p class="p-2">🐾 $<%= @dog.price %>/day</p>
  </div>
  </div>



<div class="container mt-4 d-flex justify-content-center">
<div class="form border p-4" >
 <%= render 'bookings/form', booking: @booking %>
 </div>
</div>
 <%= link_to 'Look for more Dogs', dogs_path, class: 'p-3 btn-light opacity-60 text-decoration-none' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogsForDays</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render "shared/flashes" %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Dogs For Days <strong>is the place</strong> for <strong>happiness</strong>!</h1>
    <p>Take care of Cute Dogs!</p>
     <%= link_to 'OUR PETS', dogs_path, class: 'card-category-link'%>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>

      <h1> 🐶 Dogs For Days </h1>
<%= link_to 'HOME', root_path, class: 'card-category-link'%>
</div>
  <div class="container">
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
          </li>
          <li class="nav-item">
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>